# use the latest ubuntu environment (18.04) available on travis
dist: bionic

# docker need sudo
sudo: required
services:
  - docker

# Don't email the results of the test.
notifications:
  email: false

before_install:
  - docker build -t ltdat/backend -f ops/Dockerfile .

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "backend"
  env: "Backend-env"
  bucker_name: "elasticbeanstalk-ap-southeast-1-478286478079"
  bucker_path: "backend"
  on:
    branch : master
  access_key_id: $AWS_ACCESS
  secret_access_key:
    secure: "$AWS_SECRET"
